# Generated by Django 4.2.8 on 2024-02-05 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_partpricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='partpricing',
            name='po_json',
            field=models.JSONField(null=True),
        ),
    ]
