# Generated by Django 4.2.8 on 2024-02-05 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_partpricing_po_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partpricing',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='partpricing',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
