# Generated by Django 4.2.8 on 2024-02-05 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0004_alter_partpricing_price_alter_partpricing_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partpricing',
            name='po_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
