# Generated by Django 4.2.8 on 2024-02-12 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machine_maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='machine_maintenance.line'),
        ),
        migrations.AlterField(
            model_name='maintenanceactivity',
            name='maintenance_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_activities', to='machine_maintenance.maintenanceplan'),
        ),
        migrations.AlterField(
            model_name='maintenanceplan',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_plans', to='machine_maintenance.machine'),
        ),
        migrations.AlterField(
            model_name='maintenanceplan',
            name='maintenance_activity_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_plans', to='machine_maintenance.maintenanceactivitytype'),
        ),
        migrations.AlterField(
            model_name='model',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='machine_maintenance.machine'),
        ),
    ]
