# Generated by Django 4.2.8 on 2024-02-12 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_maintenance', '0002_alter_machine_line_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceactivitytype',
            name='time',
            field=models.IntegerField(blank=True, null=True, verbose_name='Duration (minutes)'),
        ),
    ]
