# Generated by Django 4.2.8 on 2024-02-14 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_maintenance', '0003_alter_maintenanceactivitytype_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceactivity',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
