# Generated by Django 4.2.8 on 2024-03-15 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_maintenance', '0005_maintenanceplansetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceactivity',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
