# Generated by Django 4.2.8 on 2024-03-27 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_maintenance', '0006_maintenanceactivity_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceplansetting',
            name='days_to_raise_alert',
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
