# Generated by Django 4.2.8 on 2024-04-23 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_maintenance', '0007_alter_maintenanceplansetting_days_to_raise_alert'),
        ('machine_logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinelog',
            name='machine',
            field=models.ManyToManyField(related_name='machine_logs', to='machine_maintenance.machine'),
        ),
    ]
