# Generated by Django 4.2.8 on 2024-04-23 12:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machine_maintenance', '0007_alter_maintenanceplansetting_days_to_raise_alert'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('machine_logs', '0003_panel_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MachineLog',
            new_name='BoardLog',
        ),
        migrations.RenameField(
            model_name='boardlog',
            old_name='machine',
            new_name='machines',
        ),
    ]
