# Generated by Django 4.2.8 on 2024-04-24 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_maintenance', '0008_machine_log_files_folder'),
        ('machine_logs', '0004_rename_machinelog_boardlog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardlog',
            name='machines',
            field=models.ManyToManyField(to='machine_maintenance.machine'),
        ),
    ]
