# Generated by Django 4.2.8 on 2024-04-29 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_logs', '0006_alter_boardlog_panel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='serial_number',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='panel',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
