# Generated by Django 4.2.8 on 2024-01-18 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20231205_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_design_team',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='is_store_team',
            field=models.BooleanField(default=False),
        ),
    ]
