# Generated by Django 3.2.5 on 2023-12-05 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_checklist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billofmaterials',
            name='bom_file',
            field=models.FileField(blank=True, null=True, upload_to='bom_files/'),
        ),
    ]
