# Generated by Django 3.2.5 on 2023-12-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_checklist', '0002_billofmaterials_bom_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='billofmaterialslineitem',
            name='customer_part_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
