# Generated by Django 3.2.5 on 2023-12-07 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_checklist', '0004_alter_billofmaterialslineitem_bom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billofmaterialslineitem',
            name='level',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='billofmaterialslineitem',
            name='priority_level',
            field=models.CharField(max_length=4),
        ),
    ]
