# Generated by Django 3.2.5 on 2023-12-07 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_checklist', '0006_auto_20231207_0635'),
    ]

    operations = [
        migrations.AddField(
            model_name='billofmaterials',
            name='bom_file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
