# Generated by Django 3.2.5 on 2023-12-07 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_checklist', '0007_billofmaterials_bom_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billofmaterials',
            name='bom_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boms', to='store_checklist.billofmaterialstype'),
        ),
        migrations.AlterField(
            model_name='billofmaterials',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boms', to='store_checklist.product'),
        ),
        migrations.AlterField(
            model_name='billofmaterialslineitem',
            name='manufacturer_parts',
            field=models.ManyToManyField(blank=True, related_name='bom_line_items', to='store_checklist.ManufacturerPart'),
        ),
        migrations.AlterField(
            model_name='billofmaterialslineitemreference',
            name='bom_line_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='store_checklist.billofmaterialslineitem'),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='bom_line_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='store_checklist.billofmaterialslineitem'),
        ),
        migrations.AlterField(
            model_name='checklistsetting',
            name='active_bom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_settings', to='store_checklist.billofmaterials'),
        ),
        migrations.AlterField(
            model_name='manufacturerpart',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manufacturer_parts', to='store_checklist.manufacturer'),
        ),
    ]
