# Generated by Django 3.2.5 on 2023-12-08 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_checklist', '0007_billofmaterials_bom_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billofmaterialslineitemreference',
            name='bom_line_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='store_checklist.billofmaterialslineitem'),
        ),
    ]
