# Generated by Django 3.2.5 on 2023-12-08 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_checklist', '0008_auto_20231207_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='billofmaterialslineitem',
            name='uuid',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
