# Generated by Django 3.2.5 on 2023-12-08 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_checklist', '0010_auto_20231208_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist',
            name='is_passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklistsetting',
            name='active_checklist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_settings', to='store_checklist.checklist'),
        ),
    ]
