# Generated by Django 3.2.5 on 2023-12-08 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_checklist', '0011_auto_20231208_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='checklist',
            name='status',
            field=models.CharField(blank=True, choices=[('Completed', 'Completed'), ('In Progress', 'In Progress')], max_length=255, null=True),
        ),
    ]
