# Generated by Django 3.2.5 on 2023-12-08 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_checklist', '0012_auto_20231208_0942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checklistitem',
            old_name='is_checked',
            new_name='is_present',
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='is_quantity_sufficient',
            field=models.BooleanField(default=False),
        ),
    ]
