# Generated by Django 3.2.5 on 2023-12-11 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store_checklist', '0014_alter_checklist_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='assemblystage',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assemblystage_creators', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billofmaterials',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billofmaterials_creators', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billofmaterialslineitem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billofmaterialslineitem_creators', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billofmaterialslineitemreference',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billofmaterialslineitemreference_creators', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billofmaterialslineitemtype',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billofmaterialslineitemtype_creators', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billofmaterialstype',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billofmaterialstype_creators', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checklist',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_creators', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklistitem_creators', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checklistsetting',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklistsetting_creators', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manufacturer_creators', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='manufacturerpart',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manufacturerpart_creators', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_creators', to=settings.AUTH_USER_MODEL),
        ),
    ]
