# Generated by Django 3.2.5 on 2023-12-12 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_checklist', '0015_auto_20231211_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='qr_code_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checklist',
            name='unique_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
