# Generated by Django 3.2.5 on 2023-12-20 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_checklist', '0018_checklist_batch_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='qr_code_link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
