# Generated by Django 4.2.8 on 2023-12-21 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_checklist', '0021_alter_assemblystage_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billofmaterialslineitemreference',
            name='bom_line_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='references', to='store_checklist.billofmaterialslineitem'),
        ),
    ]
