# Generated by Django 4.2.8 on 2023-12-28 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_checklist', '0022_alter_billofmaterialslineitemreference_bom_line_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billofmaterialslineitem',
            name='level',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
