# Generated by Django 4.2.8 on 2024-01-05 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_checklist', '0023_alter_billofmaterialslineitem_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billofmaterialslineitem',
            name='uuid',
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='uid',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
