# Generated by Django 4.2.8 on 2024-01-05 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_checklist', '0025_remove_checklistitem_uid_checklistitemuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistitemuid',
            name='uid',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
