# Generated by Django 4.2.8 on 2024-01-25 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_checklist', '0030_alter_project_project_rev_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='billofmaterials',
            name='change_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
