# Generated by Django 4.2.8 on 2024-02-28 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_checklist', '0032_alter_project_project_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='billofmaterials',
            name='pcb_bbt_test_report_file',
            field=models.FileField(blank=True, null=True, upload_to='pcb_bbt_test_report_files/'),
        ),
    ]
