# Generated by Django 4.2.8 on 2024-03-05 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_checklist', '0034_billofmaterials_pcb_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitem',
            name='present_quantity_change_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
