# Generated by Django 4.2.8 on 2024-03-07 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_checklist', '0035_checklistitem_present_quantity_change_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='status',
            field=models.CharField(blank=True, choices=[('Completed', 'Completed'), ('In Progress', 'In Progress'), ('Failed', 'Failed'), ('Paused', 'Paused')], max_length=255, null=True),
        ),
    ]
