# Generated by Django 4.2.8 on 2024-03-27 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_checklist', '0037_alter_checklistitemuid_uid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitem',
            name='is_issued_to_production',
            field=models.BooleanField(default=False),
        ),
    ]
