# Generated by Django 4.2.8 on 2024-04-02 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_checklist', '0039_defect_inspectionboard_defecttype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defect',
            name='defect_image',
            field=models.FileField(upload_to='defect_images/'),
        ),
        migrations.AlterField(
            model_name='inspectionboard',
            name='inspection_board_image',
            field=models.FileField(upload_to='inspection_board_images/'),
        ),
    ]
