# Generated by Django 4.2.8 on 2024-04-02 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_checklist', '0040_alter_defect_defect_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defecttype',
            name='defect',
        ),
        migrations.AddField(
            model_name='defect',
            name='defect_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defects', to='store_checklist.defecttype'),
        ),
    ]
