# Generated by Django 4.2.8 on 2024-04-04 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_checklist', '0044_defect_created_at_defect_created_by_defect_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionboard',
            name='detected_board_id',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
    ]
