# Generated by Django 4.2.8 on 2024-04-04 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_checklist', '0045_inspectionboard_detected_board_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionboard',
            name='detected_board_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
