# Generated by Django 4.2.8 on 2024-04-04 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_checklist', '0046_alter_inspectionboard_detected_board_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistsetting',
            name='active_inspection_board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_settings', to='store_checklist.inspectionboard'),
        ),
    ]
