# Generated by Django 4.2.8 on 2024-04-05 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_checklist', '0047_checklistsetting_active_inspection_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='defect',
            name='defect_image_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
