# Generated by Django 5.0.6 on 2024-05-28 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_checklist', '0052_distributor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributor',
            name='api_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
