# Generated by Django 4.2.8 on 2024-06-05 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_checklist', '0053_currency_manufacturerpartdistributordetail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distributorpackagetypedetail',
            name='distributor',
        ),
        migrations.RemoveField(
            model_name='distributorpackagetypedetail',
            name='package_type',
        ),
        migrations.RemoveField(
            model_name='manufacturerpartdistributordetail',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='manufacturerpartdistributordetail',
            name='distributor',
        ),
        migrations.RemoveField(
            model_name='manufacturerpartdistributordetail',
            name='manufacturer_part',
        ),
        migrations.RemoveField(
            model_name='manufacturerpartpricing',
            name='manufacturer_part_distributor_detail',
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
        migrations.DeleteModel(
            name='DistributorPackageTypeDetail',
        ),
        migrations.DeleteModel(
            name='ManufacturerPartDistributorDetail',
        ),
        migrations.DeleteModel(
            name='ManufacturerPartPricing',
        ),
        migrations.DeleteModel(
            name='PackageType',
        ),
    ]
