# Generated by Django 4.2.8 on 2024-06-06 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_checklist', '0054_distributor_created_at_distributor_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distributor',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='distributor',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='distributor',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='distributor',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='distributor',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='distributor',
            name='access_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='distributor',
            name='access_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='distributor',
            name='api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
