# Generated by Django 4.2.8 on 2024-06-25 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_checklist', '0055_remove_distributor_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributor',
            name='api_key',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
